SELECT SCORE, HR_M.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) HR_M
JOIN HR_EMPLOYEES E ON E.EMP_NO = HR_M.EMP_NO;