-- SELECT HR_M.EMP_NO, MAX(SCORE) AS SCORE
-- FROM (

-- ) HR_M
-- WHERE SCORE = 181
-- JOIN HR_EMPLOYEES E ON E.EMP_NO = HR_M.EMP_NO;

    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    HAVING MAX(SELECT SUM(SCORE) FROM HR_GRADE)