UPDATE USED_GOODS_BOARD SET STATUS = "판매중" WHERE STATUS = 'SALE';
UPDATE USED_GOODS_BOARD SET STATUS = "예약중" WHERE STATUS = 'RESERVED';
UPDATE USED_GOODS_BOARD SET STATUS = "거래완료" WHERE STATUS = 'DONE';


SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;